services:
  db:
    image: mysql:9
    container_name: sales_tracker_db_dev
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sales_tracker-net-dev

volumes:
  db_data_dev:

networks:
  sales_tracker-net-dev: