CREATE TABLE PERSONAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
    TIPO_DOCUMENTO VARCHAR(2),
    NUMERO_DOCUMENTO VARCHAR(15)
);

CREATE TABLE PRODUCTOS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO_UNITARIO DECIMAL(6,3) NOT NULL
);

CREATE TABLE PROVEEDOR_PRODUCTO (
    PROVEEDOR_ID BIGINT NOT NULL,
    PRODUCTO_ID BIGINT NOT NULL,
    PRIMARY KEY (PROVEEDOR_ID, PRODUCTO_ID),
    FOREIGN KEY (PROVEEDOR_ID) REFERENCES PERSONAS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);

CREATE TABLE FACTURAS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE,
    VENDEDOR_ID BIGINT NOT NULL,
    CLIENTE_ID BIGINT NOT NULL,
    FOREIGN KEY (VENDEDOR_ID) REFERENCES PERSONAS(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES PERSONAS(ID)
);

CREATE TABLE DETALLES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACTURA_ID BIGINT NOT NULL,
    PRODUCTO_ID BIGINT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_VENTA DECIMAL(6,3) NOT NULL,
    FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);
